# Generated by Django 4.2.26 on 2025-12-01 10:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meeting.meeting')),
            ],
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['start_time'], name='meeting_mee_start_t_b59151_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['end_time'], name='meeting_mee_end_tim_da82ea_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['email'], name='meeting_par_email_38e4e0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('meeting', 'email')},
        ),
    ]
